#!/bin/bash
echo $*
SRC_DIR="$PWD"
PROJECT_NAME="$(sed -rne'/PROJECT *\( *([^ ]*) *\) *$/{s//\1/;p}' CMakeLists.txt)"
BUILD_DIR="/tmp/${PROJECT_NAME}-build"
CFLAGS="-Wall -g -O0"
# CXXFLAGS=$CFLAGS
# MAKE_PARAMS="VERBOSE=1"

# CMAKE_OPTS=( "" )
if [ -n "$CFLAGS" ]; then
	CMAKE_OPTS=( ${CMAKE_OPTS[@]} "-DCMAKE_C_FLAGS=$CFLAGS" )
fi

if [ -n "$CXXFLAGS" ]; then
	CMAKE_OPTS=( ${CMAKE_OPTS[@]} "-DCMAKE_CXX_FLAGS=$CXXFLAGS")
fi

if [ ! -f $BUILD_DIR/Makefile -o Makefile -ot ../CMakeList.txt ]; then
    if [ -e CMakeLists.txt ]; then
        mkdir -p $BUILD_DIR
        cd $SRC_DIR
	else
		echo '!!! NO CmakeList.txt found !!!'
		exit 1
    fi
fi

cd $BUILD_DIR
cmake "${CMAKE_OPTS[@]}" "$SRC_DIR" || exit $?


cd $BUILD_DIR
make $MAKE_PARAMS $*
exit $?
